In [1]:
import pandas as pd
import numpy as np
import data

# Master.csv

idx： 每笔贷款的unique key， 可与另外2个⽂件里的idx相匹配。

UserInfo_*： 借款⼈特征字段

WeblogInfo_*： Info⽹络⾏为字段

Education_Info*： 学历学籍字段

ThirdParty_Info_PeriodN_*： 第三⽅数据时间段N字段

SocialNetwork_*： 社交⽹络字段

LinstingInfo： 借款成交时间

Target： 违约标签（1 = 贷款违约， 0 = 正常还款） 。 测试集里不包含target字段。

In [2]:
train_master_frame,test_master_frame=data.loadMaterFrame()

In [3]:
train_master_frame.head(10)

,Idx,UserInfo_1,UserInfo_2,UserInfo_3,UserInfo_4,WeblogInfo_1,WeblogInfo_2,WeblogInfo_3,WeblogInfo_4,WeblogInfo_5,...,SocialNetwork_10,SocialNetwork_11,SocialNetwork_12,SocialNetwork_13,SocialNetwork_14,SocialNetwork_15,SocialNetwork_16,SocialNetwork_17,target,ListingInfo
0,10001,1.0,深圳,4.0,深圳,NaN,1.0,NaN,1.0,1.0,...,222,-1,0,0,0,0,0,1,0,2014/3/5
1,10002,1.0,温州,4.0,温州,NaN,0.0,NaN,1.0,1.0,...,1,-1,0,0,0,0,0,2,0,2014/2/26
2,10003,1.0,宜昌,3.0,宜昌,NaN,0.0,NaN,2.0,2.0,...,-1,-1,-1,1,0,0,0,0,0,2014/2/28
3,10006,4.0,南平,1.0,南平,NaN,NaN,NaN,NaN,NaN,...,-1,-1,-1,0,0,0,0,0,0,2014/2/25
4,10007,5.0,辽阳,1.0,辽阳,NaN,0.0,NaN,1.0,1.0,...,-1,-1,-1,0,0,0,0,0,0,2014/2/27
5,10008,1.0,吴忠,5.0,银川,NaN,0.0,NaN,2.0,2.0,...,-1,-1,-1,0,0,0,0,0,0,2014/2/27
6,10011,1.0,绵阳,3.0,赤峰,NaN,0.0,NaN,13.0,1.0,...,14,-1,0,1,0,0,0,1,1,2014/2/24
7,10015,4.0,东莞,5.0,东莞,NaN,0.0,NaN,12.0,6.0,...,559,-1,0,1,0,0,0,1,0,2014/2/28
8,10019,1.0,赤峰,6.0,赤峰,NaN,0.0,NaN,10.0,6.0,...,-1,-1,-1,0,0,0,1,0,1,2014/2/24
9,10021,3.0,武汉,5.0,鄂州,NaN,0.0,NaN,1.0,1.0,...,-1,-1,-1,1,0,0,0,0,0,2014/2/27

In [5]:
test_master_frame.head(10)

,Idx,UserInfo_1,UserInfo_2,UserInfo_3,UserInfo_4,WeblogInfo_1,WeblogInfo_2,WeblogInfo_3,WeblogInfo_4,WeblogInfo_5,...,SocialNetwork_9,SocialNetwork_10,SocialNetwork_11,SocialNetwork_12,SocialNetwork_13,SocialNetwork_14,SocialNetwork_15,SocialNetwork_16,SocialNetwork_17,ListingInfo
0,10005,1.0,广州,5.0,韶关,NaN,0.0,NaN,1.0,1.0,...,626,396,-1,0,0,0,0,0,1,21/2/2014
1,10013,4.0,郴州,6.0,广州,NaN,0.0,NaN,1.0,1.0,...,-1,-1,-1,-1,0,0,1,0,0,28/2/2014
2,10020,3.0,惠州,5.0,惠州,NaN,0.0,NaN,5.0,1.0,...,9,104,-1,0,0,0,0,0,1,23/2/2014
3,10033,1.0,枣庄,6.0,枣庄,NaN,0.0,NaN,2.0,2.0,...,62,110,-1,0,0,0,0,0,1,4/3/2014
4,10035,4.0,深圳,5.0,南平,NaN,0.0,NaN,1.0,1.0,...,-1,-1,-1,-1,0,0,0,0,0,4/3/2014
5,10038,1.0,济宁,3.0,济宁,NaN,NaN,NaN,NaN,NaN,...,-1,-1,-1,-1,0,0,0,0,0,28/2/2014
6,1004,5.0,连云港,5.0,连云港,NaN,1.0,NaN,8.0,4.0,...,5,22,-1,0,1,1,1,1,1,18/11/2013
7,10042,4.0,德州,3.0,德州,NaN,0.0,NaN,3.0,3.0,...,-1,-1,-1,-1,1,0,0,0,0,25/2/2014
8,10043,3.0,青岛,6.0,聊城,NaN,1.0,NaN,8.0,8.0,...,-1,-1,-1,-1,0,0,0,0,0,24/2/2014
9,10046,4.0,深圳,5.0,汕尾,NaN,0.0,NaN,1.0,1.0,...,357,231,-1,0,1,1,0,0,1,24/2/2014